### ISSUE TITLE
API should match client library spec

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-cocoa#2]
Specifically, the options passed to `Honeybadger.notify` should match our other libraries:

`errorString` -> `message` (or `errorMessage`)
`additionalData?` -> `context`

(not sure if there are others)

Edit: I *could* be convinced to keep `errorString`, if there is an argument that it helps make the type explicit when compared to the `error` option. When reporting an exception object in other languages, we do `Honeybadger.notify(error, options)` instead of `Honeybadger.notify(error: error, ..options)`. In any case, I want to do whatever makes the most sense for the framework or platform.

### See also

- [Client Library Spec](https://www.notion.so/honeybadger/Client-Library-Spec-aa891332f7874196aa0695b6d38dca66)
- [JavaScript options](https://docs.honeybadger.io/lib/javascript/guides/reporting-errors/#additional-options)
- [Ruby options](https://docs.honeybadger.io/lib/ruby/getting-started/reporting-errors/#passing-additional-options-to-code-honeybadger-notify-code-)

**Comment by andreybutov** [comment]
This is done in 6025ce6 . errorString retained for now as discussed. additionalData changed to context.
